mutation addInterest($interest: InterestInput!) {
  addInterest(interest: $interest ) {
    id, nickName, name, currencyPair, cbaseWalletId, wallet, isTax, soldTaxForBtc, soldTaxForEth, isReward, soldRewardForBtc, soldRewardForEth
  }
}