mutation ($nickName: String!, $name: String!, $currencyPair: String!, $walletId: String!) {
  addInterest(interest: {nickName: $nickName, name: $name, currencyPair: $currencyPair, walletId: $walletId}) {
    id,
    nickName,
    name,
    currencyPair,
    walletId
  }
}