mutation addLiquidation($liquidation: LiquidationInput!) {
  addLiquidation(liquidation: $liquidation ) {
    id, event, usdAmount, updatedAt, coin, coinAmount, model_type, liquid { coin, amount, value, updatedAt }
  }
}